apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../

namespace: prod

namePrefix: prod-

commonLabels:
  environment: production

patches:
  - path: hpa-patch.yml

images:
  - name: gcr.io/PROJECT_ID/postsappweb
    newName: gcr.io/PROJECT_ID/postsappweb
    newTag: stable