apiVersion: apps/v1
kind: Deployment
metadata:
  name: postsappweb
  labels:
    app: postsappweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postsappweb
  template:
    metadata:
      labels:
        app: postsappweb
    spec:
      containers:
      - name: postsappweb
        image: gcr.io/PROJECT_ID/postsappweb:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
        env:
        - name: NODE_ENV
          value: "production"