apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml

commonLabels:
  app: postsappweb

namespace: default

images:
  - name: gcr.io/PROJECT_ID/postsappweb
    newName: gcr.io/PROJECT_ID/postsappweb
    newTag: latest

# Create overlays directory structure for different environments
# Example usage:
# - kubectl apply -k k8s/overlays/dev
# - kubectl apply -k k8s/overlays/prod