apiVersion: v1
kind: Service
metadata:
  name: postsappweb
  labels:
    app: postsappweb
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: postsappweb
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: postsappweb-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "postsappweb-ip"
    networking.gke.io/managed-certificates: "postsappweb-cert"
spec:
  rules:
  - host: postsappweb.example.com  # Replace with your actual domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: postsappweb
            port:
              number: 80