apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../

namespace: dev

namePrefix: dev-

commonLabels:
  environment: development

patches:
  - path: replicas-patch.yml
  - path: resources-patch.yml

images:
  - name: gcr.io/PROJECT_ID/postsappweb
    newName: gcr.io/PROJECT_ID/postsappweb
    newTag: dev