name: Deploy to Google Kubernetes Engine

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: postsappweb-cluster
  GKE_ZONE: us-central1-a
  IMAGE: postsappweb

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        install_components: 'gke-gcloud-auth-plugin'

    # Configure Docker to use the gcloud command-line tool as a credential helper
    - name: Configure Docker
      run: |
        gcloud --quiet auth configure-docker

    # Build the Docker image
    - name: Build
      run: |
        docker build -t gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA .
        docker tag gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA gcr.io/$PROJECT_ID/$IMAGE:latest

    # Push the Docker image to Google Container Registry
    - name: Push
      run: |
        docker push gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
        docker push gcr.io/$PROJECT_ID/$IMAGE:latest

    # Get the GKE credentials
    - name: Set up Kubernetes credentials
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
        # Update kustomize image
        cd k8s/overlays/prod
        kustomize edit set image gcr.io/PROJECT_ID/postsappweb=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
        
        # Apply the changes
        kubectl apply -k .
        
        # Wait for the deployment to be rolled out
        kubectl rollout status deployment/prod-postsappweb -n prod